name: Auto PR for common-module changes

on:
  push:
    paths:
      - "constants-repo/**"

jobs:
  auto-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 전체 커밋 이력을 가져옵니다.

      - name: Set up Git
        run: |
          git config --global user.name "Altsoft-KimDongYoung"
          git config --global user.email "kim.dy@altsoft.kr"

      - name: Add upstream remote if not exists
        run: |
          if ! git remote | grep -q upstream; then
            git remote add upstream https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/Altsoft-KimDongYoung/0131_constants.git
          fi

      - name: Check for changes in constants-repo
        id: check_changes
        run: |
          # 이전 commit과 현재 commit 간의 변경사항을 확인합니다.
          if git diff ${{ github.event.before }} ${{ github.event.after }} --quiet --exit-code constants-repo/; then
            echo "No changes in constants-repo."
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Detected changes in constants-repo."
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create branch and push subtree if changes exist
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          # 고유한 브랜치 이름 생성 (예: auto-constants-repo-타임스탬프)
          BRANCH="auto-constants-repo-$(date +%s)"
          echo "Creating branch $BRANCH"
          git checkout -b $BRANCH
          # --squash 옵션을 사용해 커밋 이력을 단순화합니다.
          git subtree push --prefix=constants-repo upstream $BRANCH

      - name: Install GitHub CLI
        if: steps.check_changes.outputs.changes == 'true'
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Create Pull Request using GitHub CLI
        if: steps.check_changes.outputs.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Creating PR for branch $BRANCH"
          gh pr create --title "공통 모듈 자동 업데이트" \
                       --body "소비자 레포에서 감지된 constants-repo 변경사항을 upstream 저장소에 반영합니다." \
                       --base master --head $BRANCH
